apiVersion: v1
kind: ConfigMap
metadata:
  name: wazuh-manager-config
  namespace: k-guard
data:
  ossec.conf: |
    <ossec_config>
      <global>
        <jsonout_output>yes</jsonout_output>
        <alerts_log>yes</alerts_log>
        <logall>no</logall>
      </global>

      <remote>
        <connection>secure</connection>
        <port>1514</port>
        <protocol>tcp</protocol>
      </remote>

      <auth>
        <use_source_ip>yes</use_source_ip>
        <purge>yes</purge>
      </auth>
    </ossec_config>
