apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: wazuh-indexer
  namespace: k-guard
spec:
  serviceName: wazuh-indexer
  replicas: 1
  selector:
    matchLabels:
      app: wazuh-indexer
  template:
    metadata:
      labels:
        app: wazuh-indexer
    spec:
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
      containers:
      - name: wazuh-indexer
        image: wazuh/wazuh-indexer:4.14.6
        ports:
        - name: https
          containerPort: 9200
        - name: transport
          containerPort: 9300
        env:
        - name: discovery.type
          value: single-node
        - name: OPENSEARCH_INITIAL_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wazuh-indexer-credentials
              key: admin-password
        volumeMounts:
        - name: indexer-data
          mountPath: /var/lib/wazuh-indexer
        - name: indexer-config
          mountPath: /usr/share/wazuh-indexer/config/opensearch.yml
          subPath: opensearch.yml
          readOnly: true
        - name: indexer-certs
          mountPath: /usr/share/wazuh-indexer/config/certs
          readOnly: true
      volumes:
      - name: indexer-config
        configMap:
          name: wazuh-indexer-config
      - name: indexer-certs
        secret:
          secretName: wazuh-certs
  volumeClaimTemplates:
  - metadata:
      name: indexer-data
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: local-path
      resources:
        requests:
          storage: 20Gi
