apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wazuh-data-pvc
  namespace: k-guard
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wazuh-logs-pvc
  namespace: k-guard
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
