apiVersion: v1
kind: ConfigMap
metadata:
  name: wazuh-agent-config
  namespace: k-guard
  labels:
    app: wazuh-agent
    app.kubernetes.io/name: wazuh-agent
    app.kubernetes.io/part-of: k-guard
data:
  ossec.conf: |
    <ossec_config>
      <client>
        <server>
          <address>wazuh-manager-service</address>
          <port>1514</port>
          <protocol>tcp</protocol>
        </server>

        <config-profile>kubernetes</config-profile>
        <notify_time>10</notify_time>
        <time-reconnect>60</time-reconnect>
        <auto_restart>yes</auto_restart>
        <crypto_method>aes</crypto_method>

        <enrollment>
          <enabled>yes</enabled>
          <manager_address>wazuh-manager-service</manager_address>
          <port>1515</port>
          <agent_name>k8s-devopsnotes</agent_name>
        </enrollment>
      </client>

      <logging>
        <log_format>plain</log_format>
      </logging>

      <localfile>
        <log_format>syslog</log_format>
        <location>/var/log/syslog</location>
      </localfile>

      <localfile>
        <log_format>syslog</log_format>
        <location>/var/log/auth.log</location>
      </localfile>
    </ossec_config>
