# Les PVC Wazuh sont définis avec les workloads concernés.
# L'Indexer utilise volumeClaimTemplates dans wazuh-indexer.yaml.
# Le stockage persistant du Manager sera défini après analyse de wazuh-manager.yaml.
