apiVersion: v1
kind: ConfigMap
metadata:
  name: wazuh-filebeat-config
  namespace: k-guard
data:
  filebeat.yml: |
    filebeat.inputs:
      - type: log
        enabled: true
        paths:
          - /var/ossec/logs/alerts/alerts.json
        json.keys_under_root: true
        json.overwrite_keys: true
