apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: k-guard-ingress
  namespace: k-guard
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - http:
      paths:
      # 1. Kibana : On capture tout après /kibana/
      - path: /kibana/(.*)
        pathType: Prefix
        backend:
          service:
            name: kibana-kb-http
            port:
              number: 5601
      # 2. K-Guard Frontend : Capture tout le reste
      - path: /(.*)
        pathType: Prefix
        backend:
          service:
            name: k-guard-service
            port:
              number: 8000