apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: k-guard-ingress
  namespace: k-guard
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: k-guard-service
            port:
              number: 8000