# 1. ServiceAccount pour K-Guard
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k-guard-sa
  namespace: k-guard
---
# 2. ClusterRole : Observabilité et accès aux ressources du cluster
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k-guard-cluster-role
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "endpoints", "nodes", "events", "namespaces"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get", "list"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["networkpolicies"]
    verbs: ["get", "list", "watch"]
---
# 3. Role : Administration locale pour l'interface backend (ConfigMap, Secret, DaemonSet)
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: k-guard-backend-admin
  namespace: k-guard
rules:
  - apiGroups: [""]
    resources: ["secrets", "configmaps"]
    verbs: ["get", "patch", "update", "list"]
  - apiGroups: ["apps"]
    resources: ["daemonsets"]
    verbs: ["get", "patch", "update"]
---
# 4. Bindings
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k-guard-cluster-rb
subjects:
  - kind: ServiceAccount
    name: k-guard-sa
    namespace: k-guard
roleRef:
  kind: ClusterRole
  name: k-guard-cluster-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: k-guard-backend-binding
  namespace: k-guard
subjects:
  - kind: ServiceAccount
    name: k-guard-sa
    namespace: k-guard
roleRef:
  kind: Role
  name: k-guard-backend-admin
  apiGroup: rbac.authorization.k8s.io