apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
  namespace: k-guard
spec:
  version: 8.17.0
  count: 1
  elasticsearchRef:
    name: elasticsearch 
  http:
    tls:
      selfSignedCertificate:
        disabled: true
  podTemplate:
    spec:
      containers:
      - name: kibana
        resources:
          limits:
            memory: 1Gi
          requests:
            memory: 512Mi