apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
  namespace: k-guard
spec:
  version: 8.17.0
  count: 1
  config:
    server.publicBaseUrl: "http://113.30.191.17:5601"

    server.cors: true
    server.cors.allowOrigin: ["*"]

    server.xsrf.disableCookies: true

    csp.frame_ancestors: ["*"]

    xpack.security.session.idleTimeout: 30m
    xpack.security.session.lifespan: 1d

  elasticsearchRef:
    name: elasticsearch 
  http:
    tls:
      selfSignedCertificate:
        disabled: true
  podTemplate:
    spec:
      containers:
      - name: kibana
        resources:
          limits:
            memory: 1Gi
          requests:
            memory: 512Mi
