apiVersion: apps/v1
kind: Deployment
metadata:
  name: kguard-deployment-green
  namespace: k-guard-green
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: k-guard-green
  template:
    metadata:
      labels:
        app: k-guard-green
    spec:
      terminationGracePeriodSeconds: 60 
      serviceAccountName: k-guard-sa
      automountServiceAccountToken: true
      imagePullSecrets:
        - name: ghcr-secret
      securityContext:
        fsGroup: 1000
        supplementalGroups: [988]
      volumes:
        - name: docker-socket
          hostPath:
            path: /var/run/docker.sock
            type: Socket
        - name: temp-storage
          emptyDir:
            sizeLimit: 500Mi
        - name: db-storage
          hostPath:
            path: /var/lib/kguard/db
            type: DirectoryOrCreate
      containers:
        - name: kguard-app
          image: ghcr.io/kamouloxpelvis/kguard-app:v1.5.0
          imagePullPolicy: Always
          securityContext:
            runAsUser: 1000
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
              add: ["NET_ADMIN", "NET_RAW"]
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 60
            periodSeconds: 45
          volumeMounts:
            - mountPath: /var/run/docker.sock
              name: docker-socket
            - mountPath: /tmp
              name: temp-storage
            - name: db-storage
              mountPath: /app/data
          env:
            - name: K8S_MODE
              value: "in-cluster"
            - name: DB_DIR
              value: "/app/data"
          envFrom:
            - secretRef:
                name: k-guard-secrets
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
              ephemeral-storage: "500Mi"
            limits:
              cpu: 1500m
              memory: 2Gi
              ephemeral-storage: "2Gi"