apiVersion: apps/v1
kind: Deployment
metadata:
  name: kguard-deployment
  namespace: k-guard
spec:
  replicas: 1
  strategy:
    type: Recreate # Required to prevent multiple pods from locking the same PVC/SQLite DB
  selector:
    matchLabels:
      app: k-guard
  template:
    metadata:
      labels:
        app: k-guard
    spec:
      # Use the specific ServiceAccount for RBAC permissions (Pod/Deployment/Metrics list)
      serviceAccountName: k-guard-sa
      automountServiceAccountToken: true
      imagePullSecrets:
        - name: regcred

      # SecurityContext for volume permissions management
      securityContext:
        fsGroup: 1000
        supplementalGroups: [988] # Group ID for Docker socket access if needed

      volumes:
        - name: docker-socket
          hostPath:
            path: /var/run/docker.sock
            type: Socket
        - name: trivy-cache
          persistentVolumeClaim:
            claimName: trivy-cache-pvc # Storing Trivy DBs and K-Guard SQLite
      
      # InitContainer to ensure correct ownership on the Persistent Volume
      initContainers:
      - name: init-permissions
        image: busybox
        command: ["sh", "-c", "chown -R 1000:1000 /data/trivy-cache"]
        volumeMounts:
        - name: trivy-cache
          mountPath: /data/trivy-cache

      containers:
      - name: kguard-app
        image: registry.gitlab.com/portfolio-kamal-guidadou/k-guard/kguard-app:latest
        securityContext:
          runAsUser: 1000 # Running as non-root for security hardening
          allowPrivilegeEscalation: false
        ports:
        - containerPort: 8000
        volumeMounts:
          - mountPath: /var/run/docker.sock
            name: docker-socket
          - mountPath: /data/trivy-cache
            name: trivy-cache
          # Mounting SQLite database in a sub-directory of the same PVC
          - mountPath: /app/backend/data
            name: trivy-cache
            subPath: database 
        envFrom:
          - secretRef:
              name: k-guard-secrets
        
        # Liveness Probe aligned with the FastAPI /health endpoint
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 45
          periodSeconds: 30

        # SRE Resource Management
        resources:
          limits:
            cpu: "1.5"
            memory: "2Gi"
          requests:
            cpu: "500m"
            memory: "1Gi"