apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: kguard-stripper
  namespace: k-guard
spec:
  stripPrefix:
    prefixes:
      - /api

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: k-guard-ingress
  namespace: k-guard
spec:
  entryPoints:
    - web
  routes:
  # Route 1 : L'API (Prioritaire)
  - match: PathPrefix(`/api`)
    kind: Rule
    services:
    - name: k-guard-service
      port: 8000
    middlewares:
    - name: kguard-stripper

  # Route 2 : Le Frontend (Catch-all)
  - match: PathPrefix(`/`)
    kind: Rule
    services:
    - name: k-guard-frontend-service
      port: 80