apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: trivy-cache-pvc
  namespace: k-guard
spec:
  accessModes:
    - ReadWriteOnce # Standard for block storage, allows one node to mount the volume
  # 💡 NOTE: storageClassName is NOT specified here.
  # The cluster will automatically use its default Provisioner (local-path on K3s, gp2 on AWS, etc.)
  resources:
    requests:
      storage: 5Gi # Sufficient space for Trivy vulnerability DBs and K-Guard scan history