ports:
  web:
    port: 8000
    exposedPort: 80
    nodePort: 32727
  websecure:
    port: 8443
    exposedPort: 443
    nodePort: 32000

service:
  type: NodePort
  annotations: {}

ingressRoute:
  dashboard:
    enabled: true

additionalArguments:
  # On remplace proxyProtocol par forwardedHeaders car Nginx envoie du HTTP standard, pas du flux TCP Raw ProxyProtocol
  - "--entrypoints.web.forwardedHeaders.trustedIPs=127.0.0.1"
  - "--entrypoints.websecure.forwardedHeaders.trustedIPs=127.0.0.1"
  # Pour accéder au dashboard via une IngressRoute
  - "--api.dashboard=true"