apiVersion: apps/v1
kind: Deployment
metadata:
  name: falcosidekick
  namespace: falco
spec:
  replicas: 1
  selector:
    matchLabels:
      app: falcosidekick
  template:
    metadata:
      labels:
        app: falcosidekick
    spec:
      containers:
      - name: falcosidekick
        image: falcosecurity/falcosidekick:2.31.1
        args: ["--config-file", "/etc/falcosidekick/config.yaml"]
        ports:
        - containerPort: 2801
        env:
        - name: FALCOSIDEKICK_CONFIG_FILE
          value: "/etc/falcosidekick/config.yaml"
        volumeMounts:
        - name: config-volume
          mountPath: /etc/falcosidekick/config.yaml
          subPath: config.yaml
      volumes:
      - name: config-volume
        configMap:
          name: falcosidekick-config
