apiVersion: v1
kind: ConfigMap
metadata:
  name: falco-config
  namespace: k-guard
# ConfigMap : falco-config
data:
  falco.yaml: |
    engine:
      kind: modern_bpf

    stdout_output:
      enabled: true
    
    json_output: true
    log_stderr: true
    log_level: info

    rules_files:
      - /etc/falco/falco_rules.yaml
      - /etc/falco/falco_rules.local.yaml
      - /etc/falco/k8s_audit_rules.yaml