apiVersion: v1
kind: ConfigMap
metadata:
  name: falco-config
  namespace: falco
#data:
 # falco.yaml: |
  #  json_output: true
   # http_output:
    #  enabled: true
     # url: "http://falcosidekick:2801"
