apiVersion: v1
kind: ConfigMap
metadata:
  name: falcosidekick-config
  namespace: falco
data:
  config.yaml: |
    wazuh:
      checkcert: false
      host: "wazuh-events.wazuh.svc.cluster.local:1514"
