  falco:
  json_output: true
  file_output:
    enabled: true
    keepAlive: true
    path: /tmp/falco/alerts.json
  
  # Les volumes doivent être déclarés sous la clé falco 
  # ou via les valeurs spécifiques du chart
  extraVolumes:
    - name: falco-logs
      emptyDir: {}
  
  extraVolumeMounts:
    - name: falco-logs
      mountPath: /tmp/falco/
