- name: 🛡️ Network Sentinel - Stratégie de Sécurité Globale
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ns_blog: "blog-prod"
    vps_public_ip: "113.30.191.17"
    protected_namespaces: ["k-guard", "blog-prod", "portfolio-prod", "monitoring", "cert-manager"]

  tasks:
    # --- COUCHE 1 : ISOLATION TOTALE ---
    - name: "🔒 Base : Deny-All (Ingress & Egress) par défaut"
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: networking.k8s.io/v1
          kind: NetworkPolicy
          metadata:
            name: sentinel-default-deny
            namespace: "{{ item }}"
          spec:
            podSelector: {}
            policyTypes: ["Ingress", "Egress"]
      loop: "{{ protected_namespaces }}"

    # --- COUCHE 2 : INFRASTRUCTURE & DNS ---
    - name: "🔌 Infrastructure : Autoriser la Résolution DNS"
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: networking.k8s.io/v1
          kind: NetworkPolicy
          metadata:
            name: sentinel-allow-dns
            namespace: "{{ item }}"
          spec:
            podSelector: {}
            policyTypes: ["Egress"]
            egress:
              - to:
                - namespaceSelector:
                    matchLabels:
                      kubernetes.io/metadata.name: kube-system
                ports:
                  - protocol: UDP
                    port: 53
                  - protocol: TCP
                    port: 53
      loop: "{{ protected_namespaces }}"

    # --- COUCHE 3 : FLUX EXTERNES (MONGODB & GOOGLE) ---
    - name: "🌐 Cloud : Autoriser Sortie Blog -> DNS & APIs"
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: networking.k8s.io/v1
          kind: NetworkPolicy
          metadata:
            name: sentinel-allow-blog-egress-fix
            namespace: "{{ ns_blog }}"
          spec:
            podSelector:
              matchLabels:
                app: blog-devopsnotes
            policyTypes: ["Egress"]
            egress:
              - to:
                - ipBlock:
                    cidr: 0.0.0.0/0
                ports:
                  - protocol: TCP
                    port: 443   # Indispensable pour Google Indexing
                  - protocol: TCP
                    port: 27017 # MongoDB Atlas
    
    # --- COUCHE 3.5 : FLUX EXTERNES K-GUARD (WEBEX API) ---
    - name: "🌐 Cloud : Autoriser Sortie K-Guard -> Webex APIs"
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: networking.k8s.io/v1
          kind: NetworkPolicy
          metadata:
            name: sentinel-allow-kguard-egress-webex
            namespace: "k-guard"
          spec:
            podSelector:
              matchLabels:
                app: k-guard
            policyTypes: ["Egress"]
            egress:
              - to:
                - ipBlock:
                    cidr: 0.0.0.0/0
                ports:
                  - protocol: TCP
                    port: 443   # Indispensable pour l'API Webex

    # --- COUCHE 4 : MONITORING & PROBES ---
    - name: "📊 Sentinel : Autoriser le Monitoring et les Probes"
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: networking.k8s.io/v1
          kind: NetworkPolicy
          metadata:
            name: sentinel-allow-monitoring-probes
            namespace: "{{ item }}"
          spec:
            podSelector: {}
            ingress:
              - from:
                - namespaceSelector:
                    matchLabels:
                      kubernetes.io/metadata.name: monitoring
                - ipBlock:
                    cidr: 10.42.0.0/16 
      loop: "{{ protected_namespaces }}"

    # --- COUCHE 5 : GESTION INGRESS (TRAFIC WEB) ---
    - name: "🔓 Rétablissement : Autoriser Ingress -> Apps"
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: networking.k8s.io/v1
          kind: NetworkPolicy
          metadata:
            name: sentinel-allow-ingress-to-apps
            namespace: "{{ item }}"
          spec:
            podSelector: {} 
            policyTypes: ["Ingress"]
            ingress:
              - from:
                - namespaceSelector:
                    matchLabels:
                      kubernetes.io/metadata.name: ingress-nginx
                ports:
                  - protocol: TCP
                    port: 80
                  - protocol: TCP
                    port: 443
                  - protocol: TCP
                    port: 5000 
                  - protocol: TCP
                    port: 8000 
                  - protocol: TCP
                    port: 8443 
      loop: "{{ protected_namespaces }}"

    # --- COUCHE 6 : ACCÈS VPS HOST -> K-GUARD  ---
    - name: "🛡️ Sentinel : Autoriser Trafic VPS Host (Nginx) -> K-Guard"
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: networking.k8s.io/v1
          kind: NetworkPolicy
          metadata:
            name: sentinel-allow-host-to-kguard
            namespace: "k-guard"
          spec:
            podSelector:
              matchLabels:
                app: k-guard
            policyTypes: ["Ingress"]
            ingress:
              - from:
                - ipBlock:
                    cidr: "{{ vps_public_ip }}/32"
                - ipBlock:
                    cidr: 127.0.0.1/32
                ports:
                  - protocol: TCP
                    port: 8000
                  - protocol: TCP
                    port: 8443 